### ISSUE TITLE
Not able to access the send option of postfix admin

### ISSUE THREAD

**Issue by hsaklecha** [hardware/mailserver#125]
Hey,
We have successfully configured the mail server and we are able to login, we are not able to send mails through this after setting up our domain. We cannot see the option of send email also please check the screenshot.

Another issue is we are using default aliases and sending email to our gmail account but we get an error of aliases lookup fails, can you please help what are we missing.
Error - 
virtual_alias_maps map lookup problem for test@gmail.com -- message not accepted, try again later

In case of additional information please let us know.
![image](https://user-images.githubusercontent.com/16588244/27335836-743ebf54-55eb-11e7-9eeb-6d11af5ee2fa.png)

**Comment by hardware** [comment]
> We cannot see the option of send email also please check the screenshot.

Because you can't an e-mail with this postfixadmin docker image, so i disabled this option : 

https://github.com/postfixadmin/postfixadmin/blob/d2d066d13a848dd747c9bd16be5a7d33ac8a76d3/config.inc.php#L396-L398
https://github.com/hardware/postfixadmin/blob/7bccdcee621e6bf083099909aa4f6a97cc76c280/run.sh#L35
