### ISSUE TITLE
Welcome emails fail?

### ISSUE THREAD

**Issue by 1n5aN1aC** [hardware/mailserver#148]
This is very possibly something I have done to break it, but I no longer have welcome emails sent, which was nice to send IMAP login instructions with!

```
2017-08-26T23:40:05.270793+00:00 mail postfix/smtpd[18622]: connect from unknown[172.18.0.5]
2017-08-26T23:40:05.311420+00:00 mail postfix/smtpd[18622]: NOQUEUE: reject: RCPT from unknown[172.18.0.5]: 553 5.7.1 <admin@domain.tld>: Sender address rejected: not logged in; from=<admin@domain.tld> to=<newuser@domain.tld> proto=ESMTP helo=<mail.domain.tld>
```

Interestingly, they used to work, but now postfix is rejecting the email for some reason.  do you have any idea what may have caused this?  Do you think this may cause any other problems?

**Comment by hardware** [comment]
This issue is fixed in this commit : https://github.com/hardware/postfixadmin/commit/ab317941798dedf77e07c103ea7ed4c8a1c61425

> Do you have any idea what may have caused this? 

This is an intended SMTP rejection to prevent e-mail address spoofing. I use `smtpd_sender_login_maps` directive to get all addresses and alias protected by this mechanism.

```
SELECT username FROM mailbox WHERE username='%s' AND active = 1 UNION SELECT goto FROM alias WHERE address="%s" AND active = 1
```

https://github.com/hardware/mailserver/blob/d1757d5b848c3df1c700776b51f8bc1ebdcdef2e/rootfs/etc/postfix/main.cf#L95
https://github.com/hardware/mailserver/blob/d1757d5b848c3df1c700776b51f8bc1ebdcdef2e/rootfs/etc/postfix/main.cf#L155-L158

> reject_sender_login_mismatch: Reject when the client is not (SASL) logged in as that MAIL FROM address owner or when the client is (SASL) logged in, but the client login name doesn't own the MAIL FROM address.

So the solution is simple, now Postfixadmin use an e-mail address that is not used like **postfixadmin@domain.tld**. I suppose nobody will use it, so it's fine :)

**Comment by 1n5aN1aC** [comment]
Ahh, of course, that makes sense!  
Also explains why the initial account creation worked, but subsequent ones failed.

Thanks!
