### ISSUE TITLE
COnflict with : tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      3231/dnsmasq (ubuntu 16.04)

### ISSUE THREAD

**Issue by richard457** [hardware/mailserver#204]
conficting with tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      3231/dnsmasq

**Comment by maxoulamenasse** [comment]
`systemctl stop bind9` or `/etc/init.d/bind9 stop` should solve your problem.

**Comment by hardware** [comment]
You have to disable dnsmasq to run nsd on port 53. Or remove NSD service from your docker-compose file.

**Comment by richard457** [comment]
what deoes NSD will affect If I do stop it is there any way I can simply change the port it is supposed to be using instead of 53 may be can be 54 etc..

**Comment by hardware** [comment]
This docker image is useful if you need an authoritative DNS server with DNSSEC support that you manage yourself but most people use the dns system of their domain name registrar or hosting provider.

**Comment by themsay** [comment]
@hardware thanks for info. I've similar question about DNS but for now I'm using my domain registrar for DNS because of that I disabled `hardware/nsd-dnssec`. I'll like to enable it but I have no better solution.

Questions?
. Can I use both my domain registrar DNS and still use `hardware/nsd-dnssec`.
. If so, I'll like to use docker compose nds-dnssec then should I configure other docker apps running on the same system to point to this NSD.

Any idea, thanks in advance.

**Comment by hardware** [comment]
> Can I use both my domain registrar DNS and still use hardware/nsd-dnssec.

No you can't. You have to choose one.

https://calomel.org/nsd_dns.html
https://www.digitalocean.com/community/tutorials/how-to-use-nsd-an-authoritative-only-dns-server-on-ubuntu-14-04
