### ISSUE TITLE
Using mailserver as a SMTP relay

### ISSUE THREAD

**Issue by blackholegalaxy** [hardware/mailserver#237]
#### Classification

* Question
* Documentation

#### Description
Briefly describe the problem you are having in a few lines.

This mail server is a very complete solution but we struggle to get it act as a simple SMTP relay. Indeed our main usage would be:

Backend --> SMTP relay --> Real SMTP

We could then setup multiple docker running mailserver to act as multiple relays for our different customers.

Doind so prevents our backend codebase to know what SMTP is required for a given customer and can be customer agnostic. It will just send SMTP to the mailserver docker which then redirects properly the request to the real customer SMTP (we have one infrastructure by customer).

Do you think such a setup is a complex thing? I din't find anywhere on your documentation this use case.

**Comment by hardware** [comment]
> we struggle to get it act as a simple SMTP relay.

Can you describe what you have tried and and the problems that you have encountered ?

> I din't find anywhere on your documentation this use case.

This use case is not covered natively but you can customize Postfix to act as forwarder. Please, read postfix documentation for this use case.

**Comment by hardware** [comment]
Do you want to contribute to add this feature ? It will fit your needs. Besides, a relay mode could be a good addition to this project.

**Comment by navossoc** [comment]
I like to know more about. What is on your mind?

Create a new container with postfix with a custom config to just send out the messages and somehow plug it with the "main mailserver"?

**Comment by kenyee** [comment]
as a workaround, I'm trying to implement fetchmail in another container but that's turning out to be harder that it seems because of TLS certificates.
I set up IMAP mailboxes on the mailserver container, then try to use fetchmail to pull from each one by connecting to "mailserver" but then it hits the issue that the TLS certificate is from "mail.<yourdomain>".
If you can pull from the mailserver container, fetchmail and push the mail to your SMTP server.  Not quite as clean as postfix doing it for you, but probably good enough. You can probably write a script to generate the fetchmailrc file w/ all the mailbox names when you have to add new mailboxes too.

**Comment by albjeremias** [comment]
bump.
