### ISSUE TITLE
Reduce docker containers size

### ISSUE THREAD

**Issue by denji** [hardware/mailserver#26]
DockerSlim (docker-slim): Optimize and secure your Docker containers

Creating small containers requires a lot of voodoo magic and it can be pretty painful. You shouldn't have to throw away your tools and your workflow to have skinny containers. Using Docker should be easy.

docker-slim is a magic diet pill for your containers :) It will use static and dynamic analysis to create a skinny container for your app.

* https://github.com/docker-slim/docker-slim
* https://github.com/jwilder/docker-squash

**Comment by xataz** [comment]
Hi,

I look and test docker-slim, but from what I've seen, docker-slim monit i/o for use only necessary files (bin/libs etc ...).
Great for a little application, but for this container, should test any applications and all possibility for that can "sniff" necessary files.

Maybe i'm wrong.

En français au cas ou, car mon anglais est approximatif.
De ce que j'ai compris, docker-slim vérifie les i/o, et copie dans files seulement les fichiers utilisés (bin/libs etc ...).
Pour une petite application c'est pas mal, mais pour mailserver, qui a beaucoup de dépendences, il faudrait tester toutes les applications et les possibilités pour que docker-slim "sniff" les fichiers utilisés.
Mais je me trompe peu être.

XataZ

**Comment by xataz** [comment]
@denji : Why close this issue ? @hardware maybe will try, I'm not repository owner.

I try with my xataz/lstu image, for first test, i just connect on webui, without action.
After fix missing file (cpanfile), i try image creating with docker-slim, but only first page works, generate shorten uri, api page and statistics page don't works.

For second test, I create a shorten uri, go to stats and api page. This time, it's good, all work.
My image is greatly reduce (~190MB => ~23MB).

It's a great application, but i think the dockerfile generate is less readable, because it's only files copy.

En français : 
J'ai testé sur mon image xataz/lstu, pour le premier test, je me suis seulement connecté au l'interface web, sans aucune action. Après avoir corrigé un fichier manquant (cpanfile), j'ai testé l'image créé par docker-slim. Seulement la première page fonctionne, impossible de créer un lien raccourci, ou même d'aller sur la page de l'API ou des stats.

Pour mon deuxième essai, j'ai créer un lien raccourci, et je suis aller sur la page de l'api et des stats. C'est fois ci, c'est bon, tout fonctionne correctement.
L'image c'est considérablement reduite (~190MB => ~23MB).

C'est une superbe application, mais je trouve que le dockerfile généré est moins lisible, parce que c'est seulement des copies de fichiers.

**Comment by hardware** [comment]
this solution is not viable for this image.
