### ISSUE TITLE
crond.d is the wrong directory name?

### ISSUE THREAD

**Issue by j-schumann** [hardware/mailserver#36]
I think /etc/crond.d/ with the spamassassin conrjobs should be renamed to /etc/cron.d/
I suspected this jobs weren't run, so I added a job that would run every minute which wasn't run. Moving the "spamassassin" file to /etc/cron.d (next to the automatically added "amavisd-new" file) fixed this.

The amavisd-new triggers "sa-sync", this itself seems to trigger "sa-learn --sync", without specifying the "--ham" and "--spam" folders. What will "sa-learn --sync" do here, does it interfere with the ham/spam jobs?

Additionally: If the "spamassassin" file itself is left unchanged the cron will send mails with the output of the jobs to root@$hostname, the output should be redirected to syslog, a logfile or /dev/null.

**Comment by hardware** [comment]
> I think /etc/crond.d/ with the spamassassin conrjobs should be renamed to /etc/cron.d/
I suspected this jobs weren't run, so I added a job that would run every minute which wasn't run. Moving the "spamassassin" file to /etc/cron.d (next to the automatically added "amavisd-new" file) fixed this.

Wow, thank for report this, this issue will be fixed in the next commit :+1: 

> The amavisd-new triggers "sa-sync", this itself seems to trigger "sa-learn --sync", without specifying the "--ham" and "--spam" folders. What will "sa-learn --sync" do here, does it interfere with the ham/spam jobs?

This will sync any bayesian journal entries with the spamassassin's database, this task doesn't interfere with ham/spam jobs. This a slow synchronization step but necessary to deal with spam effectively.
