### ISSUE TITLE
Smart Relay Host setting

### ISSUE THREAD

**Issue by Aphris-Karu** [hardware/mailserver#363]
#### Classification
_Please delete options that are not relevant._

* [] Question
* [ ] Deliverability issue
* [ ] Crash/Hang/Data loss
* [ ] Serious bug
* [ ] Minor bug
* [ ] Vulnerability
* [X ] Feature/Enhancement
* [ ] Documentation

#### Reproducibility
_Please delete options that are not relevant._

* [] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ X] Not applicable

#### Description
To send outgoing email, I have to send it through a smart relay host (DS in sendmail) 
You really need a variable to set the smart relay host. 

Note: I really dont know postfix so not even sure how to set it in the mailserver.

**Comment by navossoc** [comment]
I'm also using a relay, so, here is how it looks like:

**/mnt/docker/mail/postfix/custom.conf**
```
# The next-hop destination of non-local mail; overrides non-local domains in recipient addresses.
relayhost = [my.relay.com]:587
```

For me, is that simple, because my servers are on the same private network, so I'm skipping authentication.

More information on how to override settings are here:
https://github.com/hardware/mailserver#override-postfix-configuration

If you need authentication, you can get some information on this sendgrid guide:
https://sendgrid.com/docs/for-developers/sending-email/postfix/

You can follow the same idea, just add the settings that you will need.
If you need to create the `password_maps` file, make sure you mount it on the host and take the appropriate steps to create the file.

I hope it helps.

[]'s

**Comment by Aphris-Karu** [comment]
navossoc, Thank you that fixed my issue!
