### ISSUE TITLE
Missing root CAs - Untrusted TLS connection

### ISSUE THREAD

**Issue by SoerenBusse** [hardware/mailserver#394]
#### Classification
_Please delete options that are not relevant._

* [ ] Question
* [ ] Deliverability issue
* [ ] Crash/Hang/Data loss
* [ ] Serious bug
* [x] Minor bug
* [ ] Vulnerability
* [ ] Feature/Enhancement
* [ ] Documentation

#### Description
When sending a mail to a ssl enabled mailserver like Google or Outlook the TLS connection is untrusted and can't be verified. 
`smtp_tls_CAfile` or better `smtp_tls_CApath` should normally contain all certificates which are trusted by postfix. By passing `$CAFILE` to `smtp_tls_CAfile` postfix is only trusting mailservers which are using this CA (when you're using a Let's Encrypt certificate only other mailservers which are using a Let's Encrypt certificate are trusted, because `$CAFILE` contains the path to the chain.pem).

We should change the postfix parameter smtp_tls_CApath to /etc/ssl/certs so postfix will trust every mailserver which is signed by one of the root CAs.
https://github.com/hardware/mailserver/blob/master/rootfs/etc/postfix/main.cf#L61

#### Steps to reproduce
1. Send a mail to any other ssl enabled mail-server

#### Expected results
After setting `smtp_tls_CApath` to `/etc/ssl/certs`
`Trusted TLS connection established to gmail-smtp-in.l.google.com[74.125.133.27]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256
`
#### Actual results
`Untrusted TLS connection established to gmail-smtp-in.l.google.com[64.233.184.27]:25: TLSv1.2 with cipher ECDHE-RSA-CHACHA20-POLY1305 (256/256 bits)
`

**Comment by hardware** [comment]
Indeed, we had already discussed this point last year with @Body4 and @navossoc but I put that aside because without this directive correctly setted, some unit tests was broken at that time. But you're right, we have to change that.

I think we can safely remove `smtp_tls_CAfile` because by default, OpenSSL uses system-supplied default Certification Authority certificates.

In this project, smtp_tls_CAfile is just useful to validate the [let's encrypt test certificate](https://github.com/hardware/mailserver/tree/master/test/share/letsencrypt/live/mail.domain.tld)

**Comment by hardware** [comment]
Fixed in https://github.com/hardware/mailserver/commit/0bf3d724cc71d8aac527fa346833c0ddef62ee3a.
