### ISSUE TITLE
Postfix missing interdem

### ISSUE THREAD

**Issue by SoerenBusse** [hardware/mailserver#398]
#### Classification
_Please delete options that are not relevant._

* [ ] Question
* [ ] Deliverability issue
* [ ] Crash/Hang/Data loss
* [X] Serious bug
* [ ] Minor bug
* [ ] Vulnerability
* [ ] Feature/Enhancement
* [ ] Documentation

#### Description
The `CERTFILE` variable contains the path to the certificate file, which doesn't include, in case of LetEncrypt, the full chain with the interdermiate certicates.

This will result in certificate validation errors:
`Certificate 1 of 1 in chain: Cert VALIDATION ERROR(S): unable to get local issuer certificate; unable to verify the first certificate`
https://www.checktls.com/TestReceiver

When using the `fullchain.pem` file everything works fine
`smtpd_tls_cert_file = /ssl/fullchain.pem`

I think this issue is related to https://github.com/hardware/mailserver/commit/0bf3d724cc71d8aac527fa346833c0ddef62ee3a

Before `smtpd_tls_CAfile` was set to `$smtp_tls_CAfile` which was then `CAFILE` assigned. This `CAFILE` contains the path to the `chain.pem`. By setting the `smtpd_tls_CAfile` to /etc/ssl/certs postfix can't find the intermediate certificates anymore.
https://github.com/hardware/mailserver/blob/0bf3d724cc71d8aac527fa346833c0ddef62ee3a/rootfs/usr/local/bin/certs_helper.sh#L16

The fix should be to change `smtpd_tls_CApath` back to  `smtpd_tls_CAfile` and assign it the `CAFILE` value. This worked in my case.
https://github.com/hardware/mailserver/commit/0bf3d724cc71d8aac527fa346833c0ddef62ee3a#diff-f81345dca28e92f7f2b99e9dbcb14d70L76

**Comment by hardware** [comment]
Good catch, fixed in https://github.com/hardware/mailserver/commit/0aa6827f71f3f0299d83f0b23770ec8b680ca60b.

> The fix should be to change smtpd_tls_CApath back to smtpd_tls_CAfile and assign it the CAFILE value. This worked in my case.

The simplest solution is to use the fullchain with `smtpd_tls_cert_file`, as dovecot with `ssl_cert`. I do not know why I forgot that |=)

So now :

* `smtp_tls_CAfile` and `smtpd_tls_CAfile` are no longer used. 
* `smtp_tls_CApath` and `smtpd_tls_CApath` are defined on `/etc/ssl/certs`
* `smtpd_tls_cert_file` is defined on `/ssl/fullchain.pem`(1)
* `smtpd_tls_key_file` is defined on `/ssl/privkey.pem`

(1) If a selfsigned certificate is used, `/ssl/fullchain.pem` contains `/ssl/cert.pem` content generated with `openssl req`.

* `CAFILE` environment variable is no longer used, but I left it in the code.

I think we're good now. Thanks for the heads up.
