### ISSUE TITLE
Outlook / Déplacement impossible

### ISSUE THREAD

**Issue by tsedgwick1** [hardware/mailserver#79]
Aléatoirement, j'ai ce message qui s'affiche, je sais pas si c'est un soucis de synchronisation mais cela empêche les mails d'être déplacé, mes clients sont en IMAP. Pour faire disparaitre l'erreur, il faut cliquer sur un autre mail de la liste puis refaire la manip.
![capture](https://cloud.githubusercontent.com/assets/17798571/22419885/c07279ae-e6df-11e6-9465-69cbba423a22.JPG)

**Comment by hardware** [comment]
C'est un problème connu de Outlook, mais ce n'est pas lié à l'image Docker. Apparemment Outlook édite le mail et empêche son déplacement pendant une l'écriture d'une réponse.  Il y a pas mal de solutions de contournement sur Google, essaye de chercher : "The operation cannot be performed because the message has been changed".
