### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by michael-k** [hardware/mailserver#94]
Have you considered switching to alpine?
- debian:jessie-slim → 30 MB vs. alpine:3.5 → 2 MB
- maria-db:10.1 → 132 MB vs. postgres:9.6-alpine → 14 MB (there's no official maria-db + alpine variant; postgres:9.6 has 102 MB)

**Comment by hardware** [comment]
> Have you considered switching to alpine ?

Yes but for stability reason, I prefer to use Debian because this docker image has a lot of components (Postfix, Dovecot, Spamassassin, Clamav, Postgrey, Fetchmail...etc), all these packages need to work together in harmony :notes: , I rely on the packages maintainers of debian for that :)

Moreover, the mail ecosystem does not need to be constantly up to date (except for security breaches).

**Comment by michael-k** [comment]
So that is the also the reason why you've put postfix and dovecot both into one image, although it's good practice to run only one daemon per container?

Btw. the alpine packages are not always up to date. Alpine 3.5 has postfix 3.1.3 and edge has 3.1.4. https://pkgs.alpinelinux.org/packages?name=postfix&branch=&repo=&arch=&maintainer=
I tried building 3.2.0 myself, but wasn't successful.

**Comment by hardware** [comment]
You are right, I could use stable packages from the main repository with v3.5 branch, but i prefer the debian freeze system which prevent a package from being updated with new features, it's more convenient for maintenance and reliability with my architectural constraints (all in one docker image).
